[package]
name = "login"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
actix-web = "4.9.0"
plugin_lib = { version = "0.1.0", path = "../../plugin_lib" }
serde = { version = "1.0.217", features = ["derive"] }
