name: Build
on:
  push:
    branches:
    - main
    paths:
    - src/**
    - Cargo.toml
    - '.github/workflows/build.yml'
env:
  PROJECT_NAME: test1_lib
jobs:
  build:
    if: '!contains(github.event.head_commit.message, ''[skip ci]'')'
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
        - name: linux-amd64
          runner: ubuntu-latest
          target: x86_64-unknown-linux-gnu
          lib-suffix: '.so'
        - name: win-amd64
          runner: windows-latest
          target: x86_64-pc-windows-msvc
          lib-suffix: '.dll'
        - name: macos-amd64
          runner: macos-latest
          target: x86_64-apple-darwin
          lib-suffix: '.dylib'
        - name: macos-arm64
          runner: macos-latest
          target: aarch64-apple-darwin
          lib-suffix: '.dylib'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    - name: Setup Cache
      uses: Swatinem/rust-cache@v2
    - name: Create Dist Directory
      run: mkdir -p dist
    - name: Build Library
      run: cargo build --verbose --locked --release --target ${{ matrix.target }}
    - name: Prepare Release Binary
      run: |
        if [[ "${{ matrix.target }}" == "x86_64-pc-windows-msvc" ]]; then
            LIB_PREFIX=""
            LIB_OUTPUT="target/${{ matrix.target }}/release/${PROJECT_NAME}${{ matrix.lib-suffix }}"
        else
            LIB_PREFIX="lib"
            LIB_OUTPUT="target/${{ matrix.target }}/release/${LIB_PREFIX}${PROJECT_NAME}${{ matrix.lib-suffix }}"
        fi
        LIB_RELEASE="${PROJECT_NAME}${{ matrix.lib-suffix }}"
        if [ ! -f "${LIB_OUTPUT}" ]; then
            echo "Library not found at ${LIB_OUTPUT}"
            exit 1
        fi
        cp "${LIB_OUTPUT}" "./dist/${LIB_RELEASE}"
        ls -l dist/
      shell: bash
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test1_lib-${{ matrix.name }}-library
        path: dist/
        retention-days: 30
